version: '3.8'

services:
  converter:
    build: .
    ports:
      - "3333:3333"
    volumes:
      - converter-data:/data
      - ../font:/app/font:ro
    environment:
      - ELECTRON_DATA_DIR=/data
    restart: unless-stopped

volumes:
  converter-data: